# Generated by Django 5.0.2 on 2026-03-14 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('house_number', models.CharField(blank=True, max_length=50)),
                ('street_name', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='India', max_length=50)),
                ('is_default_address', models.BooleanField(default=False)),
                ('is_parent', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('planning', 'Planning')], max_length=20)),
                ('baby_age_group', models.CharField(blank=True, choices=[('newborn', 'Newborn (0–3 months)'), ('infant', 'Infant (3–12 months)'), ('toddler', 'Toddler (1–3 years)'), ('preschool', 'Preschool (3+ years)')], max_length=20)),
                ('baby_gender', models.CharField(blank=True, choices=[('M', 'Boy'), ('F', 'Girl'), ('unknown', 'Not Known')], max_length=10)),
                ('pregnancy_stage', models.CharField(blank=True, choices=[('planning', 'Planning Pregnancy'), ('1st', '1st Trimester'), ('2nd', '2nd Trimester'), ('3rd', '3rd Trimester'), ('postpartum', 'Postpartum')], max_length=20)),
                ('health_condition', models.CharField(blank=True, max_length=120)),
                ('profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
